### ISSUE TITLE
Error when trying to convert map + wrong path displayed

### ISSUE THREAD

**Issue by Nic84** [coreuo/coreuo#1]
Hello,

When setting paths to convert the map the KR one is not displayed correctly:
![path](https://user-images.githubusercontent.com/11181203/112661901-cede0600-8e35-11eb-8e3d-2e28e1e30194.png)
![path2](https://user-images.githubusercontent.com/11181203/112661903-cf769c80-8e35-11eb-9669-7a3558bfa882.png)

I got this error, maybe I'm doing something wrong but... not able to convert from .mul files (ML Client 5.0.8.3 with custom modificaions to KR)
![error](https://user-images.githubusercontent.com/11181203/112661905-d0a7c980-8e35-11eb-9e62-e111e8762320.png)

OS: Win 10 64x

**Comment by coreuo** [comment]
Hello, it seems you are using an old version. Please try a newer version which is part of UltimaKR tools https://github.com/coreuo/ultimakr/releases/tag/v1.1.2

**Comment by coreuo** [comment]
I can see the bug (it is also in new version). Please specify the path manually (in textbox) for now. I will fix it in new version.
